Design and implement Login page
WebAhead-cs2/caps-look pull request #11
Opened 2023-01-29 11:42 UTC by skittan4

2023-01-29 20:14 UTC, tawfiknasser commented on src/App.js
> +  console.log(window.location.pathname)
why console log ?

2023-01-29 20:16 UTC, tawfiknasser requested changes

2023-01-29 20:16 UTC, tawfiknasser commented on src/App.js
> +  if (window.location.pathname === '/') {
Checkout another solution from react libraries.

2023-01-29 20:17 UTC, tawfiknasser commented on src/pages/Login/Login.jsx
> +function Login(){
are you using eslint ?

2023-01-29 20:18 UTC, tawfiknasser commented on src/pages/Login/Login.scss
> +h1{
better use class for specific elemnt

2023-01-29 20:19 UTC, tawfiknasser commented on src/pages/Login/Login.scss
> +background-image: url("cut.jpg");
can we use SVG instead of jpg?

2023-01-29 20:20 UTC, tawfiknasser commented on src/pages/Login/Login.scss
> +.rem{
`rem` is weird class name. because `rem` is size unit in css.

2023-01-29 20:21 UTC, tawfiknasser commented on src/pages/Login/Login.jsx
> +export default Login
add EOF

2023-01-29 23:40 UTC, Karyum commented on src/App.js
> +  if (window.location.pathname === '/') {
you could use the `useMatch` hook to make it neater, but at the end of the day `react-router-dom` uses  `window.location` 😄

2023-01-29 23:43 UTC, Karyum commented on src/pages/Login/Login.jsx
> +function Login(){
eslint could be good, but since the project is using a prettier config it's better to download the vscode extension @skittan4.
upon installing it though make sure in the settings of vscode turn on `Format on Save` and make sure the `Formatter` is set to prettier.
Then just go around and save your files, prettier will fix up the code for you and add correct indentation

2023-01-29 23:43 UTC, Karyum commented on src/pages/Login/Login.scss
> +background-image: url("cut.jpg");
can you elaborate on why @tawfiknasser ?

2023-01-30 00:01 UTC, Karyum requested changes
@skittan4 make sure to rename `Login.scss` to `Login.module.scss` this is crucial for having a smooth development on the frontend, it prevents other components or css file conflicting with yours. [here's an explanation from the `create-react-app` documentation](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)

2023-01-30 00:01 UTC, Karyum commented on package.json
> +    "primereact": "^9.0.0-beta.1",
**This is not a requested change, more of a comment**
if you want to go for a component library like `primereact` it's better off to go with a stable or matured one. either go for [Ant design](https://github.com/ant-design/ant-design) (my personal favorite) or [Google's material ui](https://mui.com/about/).

prime react has 80k downloads on npm while material UI has 2 mil

2023-01-30 00:01 UTC, Karyum commented on src/App.js
> +      </div>
```suggestion
      <div style={{textAlign:'center'}}>
       <NavBar/>
           <Login />
      </div>
```

This should be enough, we do not need the other pages or the Routes we the user is on the login page

2023-01-30 00:01 UTC, Karyum commented on src/pages/Login/Login.scss
> +height: 100vh;
with a 100vh the page is scroll (not ideal), the navbar's height is 6vh, so change this height to 94vh to hide the scrolling. (this might effect the background image size)
![asd](https://user-images.githubusercontent.com/24195641/215363532-c982b77f-d837-4377-b367-b782b3499d89.gif)

2023-01-30 06:28 UTC, tawfiknasser commented on src/pages/Login/Login.scss
> +background-image: url("cut.jpg");
Google svg vs jpg. And check if it's worth it.
Compare the output size of both formats. The final quality. Scalablity (different screens sizes).

2023-01-30 06:29 UTC, tawfiknasser commented on package.json
> +    "primereact": "^9.0.0-beta.1",
I vote up for Material UI

2023-02-02 17:30 UTC, skittan4 commented on src/pages/Login/Login.scss
> +h1{
h1 was deleted per Amdocs rep request.

2023-02-02 17:51 UTC, Karyum approved these changes
@tawfiknasser awaiting your review, removed other reviewers to speed up process

2023-02-03 09:57 UTC, tawfiknasser approved these changes

2023-02-03 09:58 UTC, merged