create button and PopUpDialog
WebAhead-cs2/caps-look pull request #41
Opened 2023-02-06 17:43 UTC by LeenMass

2023-02-06 17:46 UTC, MuhammadAw90 submitted a review, later dismissed

2023-02-07 10:08 UTC, Karyum commented
@tawfiknasser and @majdya 

I turned this into draft, just because there needs to be a discussion on who's API needs to be uploaded, we have [Amal's PR](https://github.com/WebAhead-cs2/caps-look-api/pull/27) (which is not complete by the design).
But we also have [@LeenMass working on the API for the projects](https://github.com/orgs/WebAhead-cs2/projects/2/views/1?filterQuery=GET+assignee%3ALeenMass&pane=issue&itemId=19677597), she has the completed GET request and the POST request for the projects.

2023-02-08 07:43 UTC, tawfiknasser commented
Looks good.
Can you check what the issue with the prettier?
Can you also assign more reviewers to get them engaged?

2023-02-08 07:54 UTC, tawfiknasser requested changes

2023-02-08 07:54 UTC, tawfiknasser commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
Is this route already exist in the server? 
if this code depend on code that doesn't exist yet, it will not function as expected or maybe would be broken.

2023-02-08 07:54 UTC, tawfiknasser commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
Can we extract the host name and port to an external config file?

2023-02-08 07:54 UTC, tawfiknasser commented on src/pages/Projects/PopUpDialog/index.jsx
> +      }}
any reason why using style over class ?
looks like this style can be reused and would be better to be a class

2023-02-08 07:54 UTC, tawfiknasser commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
do we expect any return status from ` await fetch` ?

2023-02-08 07:54 UTC, tawfiknasser commented on src/pages/Projects/PopUpDialog/index.jsx
> +    date: ' ',
date of what?

2023-02-08 08:05 UTC, LeenMass commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
The function is ready ,and I will create new pull request for it in the api repo now.

2023-02-08 08:31 UTC, MuhammadAw90 commented
@tawfiknasser , The error of the prettier is not clear .
we have prettier set inside the project but still we got same error every time. can you please clearly it ?

```
Run npm run prettier

> caps-lock@0.1.0 prettier
> prettier --check .

Checking formatting...
[warn] src/App.js
[warn] src/App.scss
[warn] src/components/NavBar/index.jsx
[warn] src/components/NavBar/style.module.scss
[warn] src/components/SearchBar/index.jsx
[warn] src/components/SearchBar/style.module.scss
[warn] src/components/Sidebar/index.jsx
[warn] src/components/Sidebar/style.module.scss
[warn] src/index.js
[warn] src/pages/Projects/index.jsx
[warn] src/pages/Projects/style.module.scss
[warn] src/style.module.scss
[warn] src/theme.scss
[warn] Code style issues found in [13](https://github.com/WebAhead-cs2/caps-look/actions/runs/4114735573/jobs/7102495673#step:5:14) files. Forgot to run Prettier?
Error: Process completed with exit code 1.
```

2023-02-08 08:35 UTC, tawfiknasser commented
@MuhammadAw90  what do you mean by `we have prettier set inside the project but still we got same error every time.` ? 
Is your local prettier integrated with vscode?
Is your branch updated and you are running `npm run prettier:fix` ?

2023-02-08 09:22 UTC, Karyum commented
@tawfiknasser I did not check in depth but the issue seems to be from the Github action, cause the prettier is working fine for everyone, they wouldn't need to do a  `npm run prettier:fix` since prettier fixes everything on save (we could further inforce it by adding a `settings.json` file for editor config in the project).
A guess would be  that the Github action is not caring about our prettier config, a possible fix is to add `--config .prettierrc` to the scripts

2023-02-08 09:30 UTC, tawfiknasser commented
ok, I will test it.

2023-02-08 09:43 UTC, tawfiknasser commented
@Karyum CI passed after I ran `npm run prettier:fix`

2023-02-08 09:44 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> -import { Button} from 'primereact/button'
@Karyum  no chance this was prettiered

2023-02-08 10:27 UTC, Karyum commented on src/pages/Projects/index.jsx
> -import { Button} from 'primereact/button'
Ahh nice, seems to be fixed now 😁, it's not fix on save after all. I think @tawfiknasser you should also add the following lines to `.vscode/settings.json`

```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
}
``` 

also if you really want to prevent pull requests with prettier errors, it would be much better to use [husky pre commit hooks](https://www.npmjs.com/package/husky) instead of Github actions
_also let's hope the push on development does not create merge conflicts with PRs_

2023-02-08 10:56 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> -import { Button} from 'primereact/button'
1- We can add the vscode settings. 
2- Pre commit is awesome. but it will never replace the CI pipeline. anyone can hack and cancel the pre commit because it's locally. CI is the safe side.

2023-02-08 14:17 UTC, MuhammadAw90 commented on src/pages/Projects/index.jsx
> -import { Button} from 'primereact/button'
So all i need is running this command `npm run prettier:fix`  before commit ?

2023-02-08 14:53 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> -import { Button} from 'primereact/button'
yes

2023-02-08 15:46 UTC, MuhammadAw90 commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
@tawfiknasser 
Can I put this file in same layer where package.json ?
and put it in .gitignore ?

2023-02-08 15:49 UTC, tawfiknasser commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
We should not gitignore it.
The idea is not to hard code `localhost:400` every time but having a selector where we define the host only once.

This will make it easier on us to change it later for any other host name.

2023-02-08 15:59 UTC, MuhammadAw90 commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
Okay , Thanks.
But where can i locate it ?
"Can I put the config file in same layer where package.json ?"

2023-02-08 16:42 UTC, MuhammadAw90 commented on src/pages/Projects/PopUpDialog/index.jsx
> +      await fetch('http://localhost:4000/AddingProject', {
Another question,
you asked about the response status from the await fetch, 
we have validation on the project controller, that check whether the project name exist .
but this validation won't work because the project name isn't 'Unique' currently , do you agree that we need to add to the DB table of project 'Unique' to the name of the project so the project name can't appear twice in the table and the validation will work , so we can add a validation of response status from the fetch.

2023-02-08 19:06 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> +      })
this is node/express code

2023-02-08 19:09 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> +      res.status(500).json({ message: `failed to retrieve projects, `, err })
same

2023-02-10 15:16 UTC, MuhammadAw90 approved these changes
Config file for API request

2023-02-10 16:51 UTC, tawfiknasser approved these changes

2023-02-10 16:52 UTC, merged