implementing edit project button
WebAhead-cs2/caps-look pull request #51
Opened 2023-02-09 20:47 UTC by LeenMass

2023-02-09 22:11 UTC, Karyum requested changes
Good job on this PR 🎉

2023-02-09 22:11 UTC, Karyum commented on src/components/ContentsTable/index.jsx
> +  const EditRow = (Edit) => {
having `Edit` twice like this is quite confusing (first of all use camelCase, always camelCase unless it's a component or class name).
so maybe instead we can change to this ?
```suggestion
  const [edit, setEdit] = React.useState({})

  const EditRow = (rowData) => {
```

2023-02-09 22:11 UTC, Karyum commented on src/components/ContentsTable/index.jsx
> +                    setVisible(true)
when someone clicks edit you are doing `setVisible(true)` twice, here and line 14

2023-02-09 22:11 UTC, Karyum commented on src/pages/Projects/PopUpDialog/index.jsx
> +        return 'you must to insert data'
this return doesn't do anything really, for now maybe use [the toast from prime react](https://primereact.org/toast/#severity) as a fast way to display something for the user on error or on validation fail

2023-02-09 22:11 UTC, Karyum commented on src/pages/Projects/PopUpDialog/index.jsx
> +      })
the difference between fetch and Axios 😄, we do have it in the project.
You don't need to change it, I'm just showcasing Axios
```suggestion
      await axios.post(`${process.env.REACT_APP_API_URL}/AddingProject`, body)
```

2023-02-09 22:11 UTC, Karyum commented on src/pages/Projects/PopUpDialog/index.jsx
> +    return (
This way of doing 1 component for both edit and create is fine, but you could use the same form and same state for both the edit and create. this is not a critical change, it's just nice to have. 
We can arrange a short Zoom meeting and I can explain how to do it

2023-02-09 22:11 UTC, Karyum commented on src/pages/Projects/PopUpDialog/index.jsx
> +  const formattedDate = dd + '/' + mm + '/' + yyyy
Checkout this package for date formatting https://www.npmjs.com/package/moment
it has a function called [`format()` ](https://momentjs.com/docs/#/displaying/format/) which can generate any date format

2023-02-10 16:48 UTC, MuhammadAw90 submitted a review, later dismissed

2023-02-10 16:52 UTC, saherhanif approved these changes, later dismissed

2023-02-10 17:18 UTC, MuhammadAw90 submitted a review, later dismissed
The conflict fixed

2023-02-10 17:38 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> +      const result = await fetch('http://localhost:4000/Projects')
localhost again

2023-02-10 18:15 UTC, MuhammadAw90 approved these changes, later dismissed

2023-02-10 18:27 UTC, tawfiknasser commented on src/pages/Projects/PopUpDialog/index.jsx
> +        return 'you must to insert data'
Agreed that they will add this in the upcoming PR.

2023-02-10 18:33 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> +      const result = await fetch(`${api.apiRequest}/Projects`)
project or projectPAge

2023-02-10 18:33 UTC, tawfiknasser commented on src/pages/Projects/index.jsx
> -          <Button label="Create Project" onClick={() => setVisible(true)} />
why deleted ?

2023-02-10 19:07 UTC, saherhanif approved these changes

2023-02-10 19:08 UTC, MuhammadAw90 approved these changes

2023-02-10 19:08 UTC, MuhammadAw90 commented on src/pages/Projects/index.jsx
> +      const result = await fetch(`${api.apiRequest}/Projects`)
HERE replace to /ProjectPage

2023-02-10 19:09 UTC, tawfiknasser approved these changes

2023-02-10 19:09 UTC, merged